### ISSUE TITLE
Error testing email settings

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/mailgun#1]
Craft is failing to test email settings when I add my Mailgun credentials, errors are also thrown when trying to send an email using other functions such as requesting an activation email, password reset etc.

No clue in the logs as to why this is happening.

**Comment by croxton** [comment]
On the free Mailgun account? Mailgun recently made it a requirement to add a credit card to your account if you want to send anything other than email to yourself (it's still free up to 10,000/month).

**Comment by lukeyouell** [comment]
@croxton a credit card is associated with our account and the recipeint for the test email is in the list of authorised recipients

**Comment by ryanfoote** [comment]
I'm in the same boat as @lukeyouell with the exception that I don't yet have any authorized recipients defined.

**Comment by croxton** [comment]
You could use SMTP instead of Mailgun's API (via this plugin), until this gets sorted.

**Comment by ryanfoote** [comment]
I'm getting the same "There was an error testing your email settings" error when attempting to use both the SMTP and Gmail options. Maybe this isn't an issue specific to this plugin and should be opened up in the CMS repo?

**Comment by ryanfoote** [comment]
Ah, well, let me retract my comment about Gmail. I previously tested with a GSuite account, but a plain ol' Gmail account works.

**Comment by lukeyouell** [comment]
I've had another look into this today...

I've found that the `actionTestEmailSettings()` function in `SystemSettingsController.php` doesn't log the exception as `$emailSent = $message->send()` returns `false`

This could be a Craft issue rather than a Mailgun one.

**Comment by brandonkelly** [comment]
We just released Mailgun 1.2.0, which should fix this bug.

**Comment by lukeyouell** [comment]
Cheers @brandonkelly
