### ISSUE TITLE
Can't install plugin on newer Craft versions

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/mailgun#10]
Dependencies are incompatible with latest Craft dependencies. Dependencies of this plugin should be updated.

**Comment by martyspain** [comment]
Any chance of getting this PR merged and a new point release out? I'm having the same issue with the `php-http/guzzle6-adapter` dependency being locked at `^1.1.1`.

**Comment by alexagui** [comment]
I'm running into dependency issue with Craft 3.5

---

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install craftcms/mailgun 1.4.3
    - Conclusion: don't install craftcms/mailgun 1.4.2
    - Conclusion: don't install craftcms/mailgun 1.4.1
    - Conclusion: remove symfony/console v5.1.3
    - Conclusion: don't install symfony/console v5.1.3
   - cspoo/swiftmailer-mailgun-bundle 1.0.0 requires symfony/dependency-injection ^2.7 || ^3.0 -> satisfiable by symfony/dependency-injection[v2.7.0
