### ISSUE TITLE
Transport type from environment

### ISSUE THREAD

**Issue by keyurshah** [craftcms/mailgun#12]
It seems that it is possible to set all the necessary variables from the .env file except for Transport Type. 

Is it possible to allow this setting from .env? 

I would prefer to use different transport types locally vs production. i.e. mailtrap.io (SMTP) locally and mailgun in production.

A config file would be great if that's easier.

Thanks!

**Comment by keyurshah** [comment]
Hello,

Wondering if this can be looked into. I'm currently using SMTP but it might be causing this error. 

https://github.com/craftcms/cms/issues/3224

The exact error I see for me is:

```
yii\web\BadRequestHttpExceptionGET /account/setpassword
Request missing required param
```

Thanks.

**Comment by Saboteur777** [comment]
See https://github.com/craftcms/cms/issues/2554#issuecomment-491895795

**Comment by angrybrad** [comment]
Official docs link as well for posterity: https://craftcms.com/docs/3.x/config/#mailer-component
