### ISSUE TITLE
Getting a Server Error When I try to Install Mailgun Plugin

### ISSUE THREAD

**Issue by brianrivet** [craftcms/mailgun#16]
### Description

I'm getting a server error when I try to install the Mailgun Plugin.

### Steps to reproduce

1. Added the plugin from the plugin store
2. Tried to install.

### Additional info

- Craft version: 3.5.10.1
- PHP version: 7.3
- Database driver & version: MariaDb (not sure of version #)
- Plugins & versions: Mailgun 1.4.3

**Comment by angrybrad** [comment]
Is it a general 500 Internal Server Error or something else? If it's something else, can you share the error message? If it's a Craft-generated 500 Internal Server Error, then the underlying error message should be in your Craft `storage/logs` folder. If it's a web-server generated one, it should be in your web server's error logs.

**Comment by brianrivet** [comment]
Hi Brad. I'm not sure where it is generated. I'm thinking it is probably Craft generated because the site itself isn't having a problem, the error only appears in the CP when I try to install the plugin. It's in the plugin list, but it isn't letting me install. Can I send the log file to you?

**Comment by brianrivet** [comment]
I'm looking at the Craft log and it says no plugin exists with the handle mailgun. I find that odd since it is showing up in the plugin list under settings.

**Comment by angrybrad** [comment]
@brianrivet if you open up the `craft_plugins` table in the database, do you see a row for the mailgun plugin there? If so, can you delete it and try again?

**Comment by angrybrad** [comment]
Looks like for US it's `https://api.mailgun.net/v3`

https://documentation.mailgun.com/en/latest/api-intro.html#introduction
