### ISSUE TITLE
Can't install with Craft CMS 3.5.13.2

### ISSUE THREAD

**Issue by EmptyStreets** [craftcms/mailgun#17]
- deleted the composer.lock file
- composer clear-cache

symfony/http-kernel v4.4.9 conflicts with symfony/console[v5.1.7].
Conclusion: don't install craftcms/mailgun 1.4.3
remove symfony/translation v5.1.7
install cspoo/swiftmailer-mailgun-bundle 1.0.0

--
composer.json

"require": {
    "craftcms/cms": "3.5.13.2",
    "vlucas/phpdotenv": "^2.4.0",
    "doublesecretagency/craft-smartmap": "3.3.4",
    "nystudio107/craft-seomatic": "3.3.21",
    "craftcms/redactor": "2.8.2",
    "nystudio107/craft-imageoptimize": "1.6.19",
    "nystudio107/craft-minify": "1.2.10",
    "stdauthority/smart-map-search": "*",
    "nystudio107/craft-retour": "3.1.42",
    "solspace/craft-freeform": "3.8.4",
    "yiisoft/yii2-redis": "^2.0",
    "putyourlightson/craft-campaign": "1.16.3",
    "craftcms/mailgun": "^1.4"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "optimize-autoloader": true
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
      "@composer dump-autoload -o",
      "@php craft setup/welcome"
    ]
  }
}

The recommendations in other recent 2-3 tickets haven't helped.

**Comment by EmptyStreets** [comment]
bump

**Comment by AMandujano-BI** [comment]
Same issue

**Comment by AMandujano-BI** [comment]
Did you get a solution?

**Comment by cole007** [comment]
Same issue :

Craft 3.5.10.1
Composer version 2.0.4
PHP 7.3.7
MySQL 5.7.26

```
symfony/console v5.1.8 conflicts with symfony/dependency-injection 2.7.x-dev.
symfony/console v5.1.8 conflicts with symfony/http-kernel v4.4.16.

```

**Comment by cole007** [comment]
Okay resolved - my solution  (in this order):

1. remove `vendor` folder
2. remove `composer.lock` file
3. run `composer require craftcms/mailgun`

If I do 3 after running a composer update or composer install I get the errors reported above

**Comment by hugo-costa** [comment]
Can confirm - also running into this issue.

**Comment by lesaff** [comment]
For people who are relying on Mailgun to send emails. The workaround for now is to use the SMTP method. You can grab your credentials on your Mailgun dashboard. Use port 587 and TLS as your encryption.

**Comment by angrybrad** [comment]
I'm having a hard time reproducing this. Can someone send your composer.json and composer.lock files and a database dump over to support@craftcms.com and reference this issue so we can try with that?

**Comment by angrybrad** [comment]
Going to close this out for inactivity, but if anyone is still experiencing it on the latest release of Craft (currently 3.6.12), send a database dump, and your composer.json and lock files over to support@craftmcs.com and we can look into it further.
