### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by OwenMelbz** [craftcms/mailgun#18]
### Description

Upon updating the `composer.json` with PHP 8 e.g.

```
"config": {
        "platform": {
            "php": "8.0"
        }
    },
```

Then running `composer update`

```
➜ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mailgun/mailgun-php ^3.4 -> satisfiable by mailgun/mailgun-php[3.4.0].
    - mailgun/mailgun-php 3.4.0 requires php-http/client-common ^2.2.1 -> found php-http/client-common[dev-master, 2.2.1, 2.3.0, 2.3.x-dev (alias of dev-master)] but the package is fixed to 1.10.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

  Problem 2
    - cspoo/swiftmailer-mailgun-bundle 1.2.0 requires mailgun/mailgun-php ^2.3 -> found mailgun/mailgun-php[v2.3.0, ..., 2.x-dev] but it conflicts with your root composer.json require (^3.4).
    - craftcms/mailgun 1.4.3 requires cspoo/swiftmailer-mailgun-bundle ^1.0.0 -> satisfiable by cspoo/swiftmailer-mailgun-bundle[1.2.0].
    - craftcms/mailgun is locked to version 1.4.3 and an update of this package was not requested.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

I believe because `craftcms/mailgun is locked to version 1.4.3 and an update of this package was not requested.` This means that the other dependencies cannot be updated as `craftcms/mailgun` requires specific packages at versions which do not support PHP 8?

Thanks

**Comment by angrybrad** [comment]
Unfortunately [cspoo/swiftmailer-mailgun-bundle](https://github.com/tehplague/swiftmailer-mailgun-bundle) isn’t compatible with `php-http/guzzle7-adapter`, due to a [php-http/httplug conflict](https://github.com/tehplague/swiftmailer-mailgun-bundle/issues/79). Once that is resolved, we can release a new version of Mailgun that requires Craft 3.6+ and `guzzle7-adapter` that will be PHP 8 compatible.

**Comment by angrybrad** [comment]
Also, see: https://github.com/craftcms/mailgun/issues/19#issuecomment-827213543

**Comment by OwenMelbz** [comment]
@angrybrad is there anything we can do as we're needing to try and upgrade our websites to PHP 8 but held up by this issue, hoping there's some bright ideas to accelerate this issue?

**Comment by angrybrad** [comment]
https://github.com/tehplague/swiftmailer-mailgun-bundle hasn't had activity in 2 years, so I wouldn't hold my breath.

We're also going to have to revisit all of our mail components that have dependencies on Swiftmailer anyway due to https://symfony.com/blog/the-end-of-swiftmailer, so the likely fix for this would be that move, whenever it happens.

**Comment by karensg** [comment]
Hey @angrybrad,
Can you take a look at #21 we submitted? We managed to get access and update the underlying dependency.

**Comment by brandonkelly** [comment]
@karensg That’s awesome! I’ve just pushed up a `v2` branch with `cspoo/swiftmailer-mailgun-bundle` v2.

Unfortunately it’s a bit more complicated: `mailgun/mailgun-php` v3 requires a PSR-17-compatibile PHP client, which is provided by `guzzlehttp/psr7` v2, however we are seeing Composer conflicts when requiring that, as neither `aws/aws-sdk-php` (required by our S3 plugin), nor `league/flysystem-azure-blob-storage` (required by our Azure plugin) support `guzzlehttp/psr7` v2 yet.

There is an [open issue](https://github.com/aws/aws-sdk-php/issues/2264) for `aws/aws-sdk-php`, and I’ve opened a [PR](https://github.com/thephpleague/flysystem-azure-blob-storage/pull/28) for `league/flysystem-azure-blob-storage`.

Given that this new Mailgun version is going to require PHP 7.3+ but Craft CMS ontly requires PHP 7.2.5+, and also these two first party plugin conflicts, I’m hesitant to actually tag `2.0` yet. For now, if you must use Mailgun with PHP 8 and aren’t affected by those conflicts, you can move to the `v2` branch manually by setting your `craftcms/mailgun` requirement to `"v2.x-dev"` in `composer.json`.

**Comment by karensg** [comment]
That's a shame, didn't think about that indeed.
On one of the projects it is running well with only the changes from the PR, but the Guzzle updates would be good as well.

Let's wait for the underlying plugins to get updated. We are using S3 for every project, so for now will just stick with Mailgun SMTP. No hurry here, just wanted to push this further.

🤞

**Comment by brandonkelly** [comment]
Mailgun 2.0.0 has been released! Requires Craft 3.7.20 (also just released), which now verifies that plugins’ PHP requirements are compatible with the current environment, before allowing them to be installed/updated. So no one will get an unexpected Composer error when installing the plugin if they’re running PHP 7.2.

**Comment by rikmorskate** [comment]
> @karensg That’s awesome! I’ve just pushed up a `v2` branch with `cspoo/swiftmailer-mailgun-bundle` v2.
> 
> Unfortunately it’s a bit more complicated: `mailgun/mailgun-php` v3 requires a PSR-17-compatibile PHP client, which is provided by `guzzlehttp/psr7` v2, however we are seeing Composer conflicts when requiring that, as neither `aws/aws-sdk-php` (required by our S3 plugin), nor `league/flysystem-azure-blob-storage` (required by our Azure plugin) support `guzzlehttp/psr7` v2 yet.
> 
> There is an [open issue](https://github.com/aws/aws-sdk-php/issues/2264) for `aws/aws-sdk-php`, and I’ve opened a [PR](https://github.com/thephpleague/flysystem-azure-blob-storage/pull/28) for `league/flysystem-azure-blob-storage`.
> 
> Given that this new Mailgun version is going to require PHP 7.3+ but Craft CMS ontly requires PHP 7.2.5+, and also these two first party plugin conflicts, I’m hesitant to actually tag `2.0` yet. For now, if you must use Mailgun with PHP 8 and aren’t affected by those conflicts, you can move to the `v2` branch manually by setting your `craftcms/mailgun` requirement to `"v2.x-dev"` in `composer.json`.

@brandonkelly when can your [PR](https://github.com/thephpleague/flysystem-azure-blob-storage/pull/28) be merged?

**Comment by brandonkelly** [comment]
I have no control over that.
