### ISSUE TITLE
Question: is it possible to get mailgun id after sending email?

### ISSUE THREAD

**Issue by vhontar** [craftcms/mailgun#2]
When i send email, i just have as a result only boolean true or false, but i need mailgunId for checking status of mail later, is it possible to get it after sending email?

**Comment by angrybrad** [comment]
I'm not seeing an easy way after a quick glance.  This plugins is basically a Craft wrapper for https://github.com/tehplague/swiftmailer-mailgun-bundle, which is itself a Swiftmailer wrapper for https://github.com/mailgun/mailgun-php.

The Swiftmailer wrapper only return the number of successfully sent emails: https://github.com/tehplague/swiftmailer-mailgun-bundle/blob/master/Service/MailgunTransport.php#L107-L123
