### ISSUE TITLE
V3.0 causes composer incompatibilities (With craftcms/mailgun)

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/mailgun#20]
Composeruitvoer: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- craftcms/mailgun is locked to version 1.4.3 and an update of this package was not requested.
- php-http/guzzle7-adapter 1.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0, 2.1.0, 2.2.0].
- You can only install one version of a package, so only one of these can be installed: php-http/httplug[v1.0.0, v1.1.0, v2.0.0, 2.1.0, 2.2.0].
- php-http/client-common 1.10.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
- mailgun/mailgun-php 2.8.1 requires php-http/client-common ^1.1 -> satisfiable by php-http/client-common[1.10.0].
- craftcms/commerce-omnipay 3.0.0 requires php-http/guzzle7-adapter ^1.0 -> satisfiable by php-http/guzzle7-adapter[1.0.0].
- cspoo/swiftmailer-mailgun-bundle 1.2.0 requires mailgun/mailgun-php ^2.3 -> satisfiable by mailgun/mailgun-php[2.8.1].
- craftcms/commerce-mollie 3.0.0 requires craftcms/commerce-omnipay ^3.0 -> satisfiable by craftcms/commerce-omnipay[3.0.0].
- craftcms/mailgun 1.4.3 requires cspoo/swiftmailer-mailgun-bundle ^1.0.0 -> satisfiable by cspoo/swiftmailer-mailgun-bundle[1.2.0].
- Root composer.json requires craftcms/commerce-mollie 3.0.0 -> satisfiable by craftcms/commerce-mollie[3.0.0].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

**Comment by nfourtythree** [comment]
This is essentially the same issue as #19 

Closing this for, please follow the issue mentioned above for updates.

Thanks!

**Comment by brandonkelly** [comment]
There is now a `v2` branch with Guzzle 7 / PHP 8 support, with caveats. see https://github.com/craftcms/mailgun/issues/18#issuecomment-920293302.
