### ISSUE TITLE
Broken link under Setup in Readme.md docs

### ISSUE THREAD

**Issue by mattias78** [craftcms/mailgun#25]
### Description

Broken link to Mailgun domains under 'Setup' in Readme.md docs

Once Mailgun is installed, go to Settings → Email, and change the “Transport Type” setting to “Mailgun”. Enter your domain name and Mailgun API Key (which you can get from your [domain overview](https://mailgun.com/app/domains) page) and click Save.

**Comment by angrybrad** [comment]
Thanks... fixed!
