### ISSUE TITLE
Add support for EU Region

### ISSUE THREAD

**Issue by stereomyth** [craftcms/mailgun#3]
Mailgun have added an EU region with a different API address `https://api.eu.mailgun.net`.

I imagine this could just be a region dropdown on the setting page.

[Press release](https://www.mailgun.com/blog/we-have-a-new-region-in-europe-yall)

**Comment by meredevelopment** [comment]
According to [this comment](https://github.com/mailgun/mailgun-php/issues/471#issuecomment-408623386) on the mailgun-php repo, it looks like support for a different region can be achieved by allowing `setEndpoint` to be set for the `HttpClientConfigurator` that's setup here: https://github.com/craftcms/mailgun/blob/v1/src/MailgunAdapter.php#L90 

I don't have a way of testing this, and I've been using Craft for a few days so I think someone else would be better of creating a PR etc 😖

**Comment by Saboteur777** [comment]
:+1:  on this. :slightly_smiling_face:

**Comment by brandonkelly** [comment]
This was resolved by #4. We just released version 1.3.0 with that.
