### ISSUE TITLE
Endpoint is not a valid URL. when using .env variable

### ISSUE THREAD

**Issue by kobeaerts** [craftcms/mailgun#7]
I can't seem to save my mailgun settings when using a .env variable in the api-endpoint field.

.env name: `$MAILGUN_API_ENDPOINT`
`MAILGUN_API_ENDPOINT="https://api.mailgun.net/v3/webosaurus.be"`

The domain and api-key field do work with it.

**Comment by brandonkelly** [comment]
Just released v1.4.1 with a fix for this. Thanks for reporting!

**Comment by kobeaerts** [comment]
Hey @brandonkelly is it possible this isn't released on packagist yet?
Anyway, thanks for the fast fix!

**Comment by brandonkelly** [comment]
@kobeaerts Yeah sorry, just _really_ released 1.4.1 :)
