### ISSUE TITLE
Difference between settings Mailgun credentials as SMTP settings / Mailgun plugin?

### ISSUE THREAD

**Issue by mdominguez** [craftcms/mailgun#9]
Hi

What's the difference between having set Mailgun SMTP authentication settings (with username & pass) for delivering emails through Craft and the usage of this plugin (so no authentication takes place)?
Isn't SMTP much safer / more likely to be delivered?

We have been using this Mailgun plugin for a couple of years now and apparently some random e-mails (like 1 in the 500) don't even reach Mailgun, whilst they are clearly entered and available in the CMS (as a Freeform submission). Unfortunately nothing related to this undelivered email is found in any of the Craft, Freeform or server logs whatsoever.. Pulling our hair out on this as we can't seem to sort out what is causing this random undeliverable emails... :)

**Comment by angrybrad** [comment]
> What's the difference between having set Mailgun SMTP authentication settings (with username & pass) for delivering emails through Craft and the usage of this plugin (so no authentication takes place)?

The former uses the SMTP protocol and the latter is going directly through their API https://documentation.mailgun.com/en/latest/api_reference.html (which you still have to provide an API key for).

> Isn't SMTP much safer / more likely to be delivered?

I would think the API would be more reliable. As to your issue, you can try checking the Craft/Freeform logs, but if it's 1 in 500, there's a chance any error message would have been rotated out of the logs already.

**Comment by mdominguez** [comment]
Unfortunately nothing related to freeform nor mailgun was found in the logs of that day... It's like nothing happened, only a submission in the CMS :/
